// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { blogPostsMeta } from "npm:@/data/blogPostsMeta";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "Listar art\xEDculos del blog",
  description: "Devuelve la lista de art\xEDculos publicados en el blog de Neoka (slug, t\xEDtulo, fecha, tiempo de lectura y meta descripci\xF3n).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = blogPostsMeta.map((p) => ({
      slug: p.slug,
      title: p.title,
      date: p.date,
      readTime: p.readTime,
      metaDescription: p.metaDescription,
      url: `https://www.centroneoka.es/blog/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
import { blogPostsMeta as blogPostsMeta2 } from "npm:@/data/blogPostsMeta";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Obtener art\xEDculo del blog",
  description: "Devuelve los metadatos y la URL p\xFAblica de un art\xEDculo del blog de Neoka por su slug.",
  inputSchema: {
    slug: z.string().min(1).describe("Slug del art\xEDculo, p. ej. 'comunicacion-asertiva-pareja'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPostsMeta2.find((p) => p.slug === slug);
    if (!post) {
      return {
        content: [{ type: "text", text: `No se encontr\xF3 ning\xFAn art\xEDculo con slug "${slug}".` }],
        isError: true
      };
    }
    const data = {
      slug: post.slug,
      title: post.title,
      date: post.date,
      readTime: post.readTime,
      metaTitle: post.metaTitle,
      metaDescription: post.metaDescription,
      url: `https://www.centroneoka.es/blog/${post.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var services = [
  { name: "Psicolog\xEDa Sanitaria", path: "/psicologia-sanitaria" },
  { name: "Terapia de Pareja", path: "/terapia-pareja" },
  { name: "Terapia Transpersonal", path: "/terapia-transpersonal" },
  { name: "Fisioterapia", path: "/fisioterapia" },
  { name: "Podolog\xEDa", path: "/podologia" },
  { name: "Nutrici\xF3n y Diet\xE9tica", path: "/nutricion-dietetica" }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "Listar servicios",
  description: "Devuelve los servicios ofrecidos por Neoka - Centro de Psicolog\xEDa, Terapia de Pareja y Coaching en Huelva.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = services.map((s) => ({
      ...s,
      url: `https://www.centroneoka.es${s.path}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Informaci\xF3n de contacto",
  description: "Devuelve el nombre, direcci\xF3n, tel\xE9fono, WhatsApp, web y n\xFAmero de registro sanitario (NICA) de Neoka.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      name: "Neoka - Centro de Psicolog\xEDa, Terapia de Pareja y Coaching",
      address: "C. la Palma, 4, Local derecha, 21002 Huelva",
      phone: "+34 617 64 25 64",
      whatsapp: "https://wa.me/34617642564",
      website: "https://www.centroneoka.es",
      googleMaps: "https://www.google.com/maps/search/?api=1&query=Neoka+Centro+de+Psicolog%C3%ADa+Huelva",
      nica: "60441"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "neoka-mcp",
  title: "Neoka - Centro de Salud Integral",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas de Neoka (Huelva): consulta de art\xEDculos del blog, servicios ofrecidos e informaci\xF3n de contacto oficial del centro.",
  tools: [list_blog_posts_default, get_blog_post_default, list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
