// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/data/blogPostsMeta.ts
var blogPostsMeta = [
  {
    slug: "comunicacion-asertiva-pareja",
    title: "5 Claves para mejorar la comunicaci\xF3n asertiva en tu relaci\xF3n.",
    date: "15 abr 2026",
    readTime: "5 Min. de lectura",
    metaTitle: "5 Claves para la comunicaci\xF3n asertiva en pareja | Terapia de Pareja Huelva",
    metaDescription: "Descubre las 5 claves esenciales para mejorar la comunicaci\xF3n asertiva en tu relaci\xF3n de pareja. Escucha activa, validaci\xF3n emocional y m\xE1s consejos profesionales."
  },
  {
    slug: "el-amor-se-ha-perdido",
    title: "El amor se ha perdido.",
    date: "8 may 2024",
    readTime: "4 Min. de lectura",
    metaTitle: "El amor se ha perdido | Reflexiones de Terapia de Pareja - Neoka Huelva",
    metaDescription: "Reflexi\xF3n profesional sobre c\xF3mo se transforma el amor con el tiempo y cu\xE1ndo acudir a terapia de pareja en Huelva."
  },
  {
    slug: "mirar-hacia-otro-lado",
    title: "Mirar hacia otro lado",
    date: "1 may 2024",
    readTime: "4 Min. de lectura",
    metaTitle: "Mirar hacia otro lado | Blog de Psicolog\xEDa - Neoka Huelva",
    metaDescription: "Art\xEDculo sobre el mecanismo de evitaci\xF3n emocional y c\xF3mo la psicoterapia ayuda a afrontar aquello que evitamos."
  },
  {
    slug: "la-importancia-del-compromiso",
    title: "La importancia del compromiso.",
    date: "11 oct 2023",
    readTime: "4 Min. de lectura",
    metaTitle: "La importancia del compromiso en pareja | Neoka Huelva",
    metaDescription: "Por qu\xE9 el compromiso es un pilar de la relaci\xF3n de pareja y c\xF3mo trabajarlo desde la terapia."
  },
  {
    slug: "perderse-encontrarse-catarsis",
    title: "Perderse - Encontrarse = Catarsis.",
    date: "8 jun 2023",
    readTime: "4 Min. de lectura",
    metaTitle: "Perderse y encontrarse: la catarsis emocional | Neoka Huelva",
    metaDescription: "Reflexi\xF3n sobre la catarsis emocional en los procesos de autoconocimiento y terapia."
  },
  {
    slug: "idolos-del-circo",
    title: "\xCDdolos del circo.",
    date: "20 sept 2020",
    readTime: "4 Min. de lectura",
    metaTitle: "\xCDdolos del circo | Blog de Psicolog\xEDa - Neoka Huelva",
    metaDescription: "Art\xEDculo del blog de Neoka sobre modelos y referentes sociales."
  },
  {
    slug: "bendito-2020",
    title: "Bendito 2020.",
    date: "11 dic 2020",
    readTime: "4 Min. de lectura",
    metaTitle: "Bendito 2020 | Blog de Psicolog\xEDa - Neoka Huelva",
    metaDescription: "Reflexi\xF3n sobre el a\xF1o 2020 y sus aprendizajes emocionales."
  }
];

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "Listar art\xEDculos del blog",
  description: "Devuelve la lista de art\xEDculos publicados en el blog de Neoka (slug, t\xEDtulo, fecha, tiempo de lectura y meta descripci\xF3n).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = blogPostsMeta.map((p) => ({
      slug: p.slug,
      title: p.title,
      date: p.date,
      readTime: p.readTime,
      metaDescription: p.metaDescription,
      url: `https://www.centroneoka.es/blog/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Obtener art\xEDculo del blog",
  description: "Devuelve los metadatos y la URL p\xFAblica de un art\xEDculo del blog de Neoka por su slug.",
  inputSchema: {
    slug: z.string().min(1).describe("Slug del art\xEDculo, p. ej. 'comunicacion-asertiva-pareja'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPostsMeta.find((p) => p.slug === slug);
    if (!post) {
      return {
        content: [{ type: "text", text: `No se encontr\xF3 ning\xFAn art\xEDculo con slug "${slug}".` }],
        isError: true
      };
    }
    const data = {
      slug: post.slug,
      title: post.title,
      date: post.date,
      readTime: post.readTime,
      metaTitle: post.metaTitle,
      metaDescription: post.metaDescription,
      url: `https://www.centroneoka.es/blog/${post.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var services = [
  { name: "Psicolog\xEDa Sanitaria", path: "/psicologia-sanitaria" },
  { name: "Terapia de Pareja", path: "/terapia-pareja" },
  { name: "Terapia Transpersonal", path: "/terapia-transpersonal" },
  { name: "Fisioterapia", path: "/fisioterapia" },
  { name: "Podolog\xEDa", path: "/podologia" },
  { name: "Nutrici\xF3n y Diet\xE9tica", path: "/nutricion-dietetica" }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "Listar servicios",
  description: "Devuelve los servicios ofrecidos por Neoka - Centro de Psicolog\xEDa, Terapia de Pareja y Coaching en Huelva.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = services.map((s) => ({
      ...s,
      url: `https://www.centroneoka.es${s.path}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Informaci\xF3n de contacto",
  description: "Devuelve el nombre, direcci\xF3n, tel\xE9fono, WhatsApp, web y n\xFAmero de registro sanitario (NICA) de Neoka.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      name: "Neoka - Centro de Psicolog\xEDa, Terapia de Pareja y Coaching",
      address: "C. la Palma, 4, Local derecha, 21002 Huelva",
      phone: "+34 617 64 25 64",
      whatsapp: "https://wa.me/34617642564",
      website: "https://www.centroneoka.es",
      googleMaps: "https://www.google.com/maps/search/?api=1&query=Neoka+Centro+de+Psicolog%C3%ADa+Huelva",
      nica: "60441"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "neoka-mcp",
  title: "Neoka - Centro de Salud Integral",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas de Neoka (Huelva): consulta de art\xEDculos del blog, servicios ofrecidos e informaci\xF3n de contacto oficial del centro.",
  tools: [list_blog_posts_default, get_blog_post_default, list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
